package com.newsjet.jethome.dao.mapper;

import com.newsjet.jethome.dao.entity.CommentTemplate;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import java.util.List;

public interface CommentTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_template
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_template
     *
     * @mbggenerated
     */
    int insert(CommentTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_template
     *
     * @mbggenerated
     */
    int insertSelective(CommentTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_template
     *
     * @mbggenerated
     */
    CommentTemplate selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_template
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CommentTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_template
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(CommentTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment_template
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CommentTemplate record);

    @Select("select * from comment_template limit #{from}, #{size} order by id desc")
    List<CommentTemplate> selectRange(@Param("from") Integer from, @Param("size") Integer size);

    @Select("select * from comment_template where cid = 'all' or cid = #{cid} order by rand() limit #{limit}")
    List<CommentTemplate> selectApplicableRandomly(@Param("cid") String cid, @Param("limit") Integer limit);
}