package com.newsjet.jethome.dao.mapper;

import com.newsjet.jethome.dao.entity.NewsUpload;
import com.newsjet.jethome.dao.entity.NewsUploadWithBLOBs;

public interface NewsUploadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_upload
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_upload
     *
     * @mbggenerated
     */
    int insert(NewsUploadWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_upload
     *
     * @mbggenerated
     */
    int insertSelective(NewsUploadWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_upload
     *
     * @mbggenerated
     */
    NewsUploadWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_upload
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(NewsUploadWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_upload
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(NewsUploadWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news_upload
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(NewsUpload record);
}