package com.newsjet.jethome.dao.entity;

import java.io.Serializable;

public class NewsUploadWithBLOBs extends NewsUpload implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_upload.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_upload.image1
     *
     * @mbggenerated
     */
    private String image1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_upload.image2
     *
     * @mbggenerated
     */
    private String image2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_upload.image3
     *
     * @mbggenerated
     */
    private String image3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table news_upload
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_upload.content
     *
     * @return the value of news_upload.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_upload.content
     *
     * @param content the value for news_upload.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_upload.image1
     *
     * @return the value of news_upload.image1
     *
     * @mbggenerated
     */
    public String getImage1() {
        return image1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_upload.image1
     *
     * @param image1 the value for news_upload.image1
     *
     * @mbggenerated
     */
    public void setImage1(String image1) {
        this.image1 = image1 == null ? null : image1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_upload.image2
     *
     * @return the value of news_upload.image2
     *
     * @mbggenerated
     */
    public String getImage2() {
        return image2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_upload.image2
     *
     * @param image2 the value for news_upload.image2
     *
     * @mbggenerated
     */
    public void setImage2(String image2) {
        this.image2 = image2 == null ? null : image2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_upload.image3
     *
     * @return the value of news_upload.image3
     *
     * @mbggenerated
     */
    public String getImage3() {
        return image3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_upload.image3
     *
     * @param image3 the value for news_upload.image3
     *
     * @mbggenerated
     */
    public void setImage3(String image3) {
        this.image3 = image3 == null ? null : image3.trim();
    }
}