package com.newsjet.jethome.dao.entity;

import java.io.Serializable;
import java.util.Date;

public class NewsUpload implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_upload.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_upload.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_upload.source
     *
     * @mbggenerated
     */
    private String source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_upload.publish_time
     *
     * @mbggenerated
     */
    private Date publishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_upload.url
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_upload.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_upload.category_id
     *
     * @mbggenerated
     */
    private String categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_upload.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_upload.site
     *
     * @mbggenerated
     */
    private String site;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_upload.relatedTitle1
     *
     * @mbggenerated
     */
    private String relatedtitle1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_upload.relatedLink1
     *
     * @mbggenerated
     */
    private String relatedlink1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_upload.relatedTitle2
     *
     * @mbggenerated
     */
    private String relatedtitle2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_upload.relatedLink2
     *
     * @mbggenerated
     */
    private String relatedlink2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_upload.relatedTitle3
     *
     * @mbggenerated
     */
    private String relatedtitle3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news_upload.relatedLink3
     *
     * @mbggenerated
     */
    private String relatedlink3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table news_upload
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_upload.id
     *
     * @return the value of news_upload.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_upload.id
     *
     * @param id the value for news_upload.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_upload.title
     *
     * @return the value of news_upload.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_upload.title
     *
     * @param title the value for news_upload.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_upload.source
     *
     * @return the value of news_upload.source
     *
     * @mbggenerated
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_upload.source
     *
     * @param source the value for news_upload.source
     *
     * @mbggenerated
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_upload.publish_time
     *
     * @return the value of news_upload.publish_time
     *
     * @mbggenerated
     */
    public Date getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_upload.publish_time
     *
     * @param publishTime the value for news_upload.publish_time
     *
     * @mbggenerated
     */
    public void setPublishTime(Date publishTime) {
        this.publishTime = publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_upload.url
     *
     * @return the value of news_upload.url
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_upload.url
     *
     * @param url the value for news_upload.url
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_upload.create_time
     *
     * @return the value of news_upload.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_upload.create_time
     *
     * @param createTime the value for news_upload.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_upload.category_id
     *
     * @return the value of news_upload.category_id
     *
     * @mbggenerated
     */
    public String getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_upload.category_id
     *
     * @param categoryId the value for news_upload.category_id
     *
     * @mbggenerated
     */
    public void setCategoryId(String categoryId) {
        this.categoryId = categoryId == null ? null : categoryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_upload.status
     *
     * @return the value of news_upload.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_upload.status
     *
     * @param status the value for news_upload.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_upload.site
     *
     * @return the value of news_upload.site
     *
     * @mbggenerated
     */
    public String getSite() {
        return site;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_upload.site
     *
     * @param site the value for news_upload.site
     *
     * @mbggenerated
     */
    public void setSite(String site) {
        this.site = site == null ? null : site.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_upload.relatedTitle1
     *
     * @return the value of news_upload.relatedTitle1
     *
     * @mbggenerated
     */
    public String getRelatedtitle1() {
        return relatedtitle1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_upload.relatedTitle1
     *
     * @param relatedtitle1 the value for news_upload.relatedTitle1
     *
     * @mbggenerated
     */
    public void setRelatedtitle1(String relatedtitle1) {
        this.relatedtitle1 = relatedtitle1 == null ? null : relatedtitle1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_upload.relatedLink1
     *
     * @return the value of news_upload.relatedLink1
     *
     * @mbggenerated
     */
    public String getRelatedlink1() {
        return relatedlink1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_upload.relatedLink1
     *
     * @param relatedlink1 the value for news_upload.relatedLink1
     *
     * @mbggenerated
     */
    public void setRelatedlink1(String relatedlink1) {
        this.relatedlink1 = relatedlink1 == null ? null : relatedlink1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_upload.relatedTitle2
     *
     * @return the value of news_upload.relatedTitle2
     *
     * @mbggenerated
     */
    public String getRelatedtitle2() {
        return relatedtitle2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_upload.relatedTitle2
     *
     * @param relatedtitle2 the value for news_upload.relatedTitle2
     *
     * @mbggenerated
     */
    public void setRelatedtitle2(String relatedtitle2) {
        this.relatedtitle2 = relatedtitle2 == null ? null : relatedtitle2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_upload.relatedLink2
     *
     * @return the value of news_upload.relatedLink2
     *
     * @mbggenerated
     */
    public String getRelatedlink2() {
        return relatedlink2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_upload.relatedLink2
     *
     * @param relatedlink2 the value for news_upload.relatedLink2
     *
     * @mbggenerated
     */
    public void setRelatedlink2(String relatedlink2) {
        this.relatedlink2 = relatedlink2 == null ? null : relatedlink2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_upload.relatedTitle3
     *
     * @return the value of news_upload.relatedTitle3
     *
     * @mbggenerated
     */
    public String getRelatedtitle3() {
        return relatedtitle3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_upload.relatedTitle3
     *
     * @param relatedtitle3 the value for news_upload.relatedTitle3
     *
     * @mbggenerated
     */
    public void setRelatedtitle3(String relatedtitle3) {
        this.relatedtitle3 = relatedtitle3 == null ? null : relatedtitle3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news_upload.relatedLink3
     *
     * @return the value of news_upload.relatedLink3
     *
     * @mbggenerated
     */
    public String getRelatedlink3() {
        return relatedlink3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news_upload.relatedLink3
     *
     * @param relatedlink3 the value for news_upload.relatedLink3
     *
     * @mbggenerated
     */
    public void setRelatedlink3(String relatedlink3) {
        this.relatedlink3 = relatedlink3 == null ? null : relatedlink3.trim();
    }

    @Override
    public String toString() {
        return "NewsUpload{" +
                "id='" + id + '\'' +
                ", title='" + title + '\'' +
                ", source='" + source + '\'' +
                ", publishTime=" + publishTime +
                ", url='" + url + '\'' +
                ", createTime=" + createTime +
                ", categoryId='" + categoryId + '\'' +
                ", status=" + status +
                ", site='" + site + '\'' +
                ", relatedtitle1='" + relatedtitle1 + '\'' +
                ", relatedlink1='" + relatedlink1 + '\'' +
                ", relatedtitle2='" + relatedtitle2 + '\'' +
                ", relatedlink2='" + relatedlink2 + '\'' +
                ", relatedtitle3='" + relatedtitle3 + '\'' +
                ", relatedlink3='" + relatedlink3 + '\'' +
                '}';
    }
}